In [32]:
import pandas as pd
df = pd.read_csv('Noida2.csv', encoding='unicode_escape')
new_header = df.iloc[0]
df = df[1:]
df.columns = new_header 
columns = list(df.columns)
columns = [x for x in columns if str(x) != 'nan' and str(x) != 'Correct Answers']
columns
for col in columns:
    df[col] = df[col] == col
df.head() 
df['Correct Answer'] = (df == True).sum(axis =1)
df.to_csv('result.csv')

,nan,nan,Jai Prakash,Parnika,Divya Goel,Akshay saxena,Manav Gogia,Garima Jain,Rishabh Mendiratta,Ankur Jindal,...,Sahil Gupta,Vasudha Chopra,Anubha Kansil,Pankaj Sadhwani,Karan Sadh,Utkarsh Jain,Manmohan Singh,Ankit Ahuja,Manish Prasad,Correct Answers
1,11/14/2019 15:20:51,sukriti.kukrety@visiblealpha.com,False,True,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,4
2,11/14/2019 15:20:51,himanshu.jain@visiblealpha.com,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,5
3,11/14/2019 15:24:12,parnika.agarwal@visiblealpha.com,False,False,False,False,False,True,False,False,...,True,False,True,False,True,False,False,False,True,6
4,11/14/2019 15:25:33,rachita.rajput@visiblealpha.com,False,True,False,False,False,True,False,False,...,True,False,True,False,True,False,False,False,True,7